# Generated by Django 2.2.12 on 2021-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('main_desc', models.CharField(max_length=100)),
                ('portfolios', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
            ],
        ),
    ]
